# Generated by Django 2.2.7 on 2019-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_primary_fridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='primary_fridge',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
