# Generated by Django 2.2.7 on 2019-11-14 13:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='auto_gen_grocery_list',
            field=django_mysql.models.ListTextField(models.CharField(max_length=15), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='friends',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='manually_added_list',
            field=django_mysql.models.ListTextField(models.CharField(max_length=15), default=[], size=None),
        ),
    ]
