# Generated by Django 2.2.7 on 2019-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator_app', '0002_auto_20191114_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageurl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sourceurl',
            field=models.TextField(null=True),
        ),
    ]
